baseURL = "https://sam6255.github.io/"
languageCode = "en-us"
title = "宁静致远"
theme = "ezhil"
publishDir = "sam6255.github.io"

pygmentsstyle = "vs"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

googleAnalytics = "UA-123-45"
#disqusShortname = ""

[params]
	subtitle = "千里之行始于足下"
	# Number of posts to show in recent posts list.
	recentPostsCount = 50
	# Content types which are excluded from recent posts and archive page.
	excludedTypes = ["page"]
	disableDisqusTypes = ["page"]
	featherIconsCDN = true

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "articles"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "tags"
url = "/tags"
weight = 4

[[params.social]]
name = "Github"
icon = "github"
url = "https://gitee.com/nbocean"

[taxonomies]
   tag = "tags"
